---
- hosts: webservers
  remote_user: ec2-user
  sudo: yes 
  tasks:
   - name: ensure apache is at the latest version
     yum: name=httpd state=latest
   - name: install mod_ssl
     yum: pkg=mod24_ssl state=latest
   - name: copy cert key
     copy: src=/SREChallenge/ansible/certs/mysitename.key dest=/etc/httpd/conf/mysitename.key backup=yes
   - name: copy cert
     copy: src=/SREChallenge/ansible/certs/mysitename.crt dest=/etc/httpd/conf/mysitename.crt backup=yes
   - name: overrite apache config file
     copy: src=/SREChallenge/config/httpd.conf dest=/etc/httpd/conf/httpd.conf backup=yes
   - name: Create a sample directory
     file: path=/var/www/html/Sample state=directory mode=0755 owner=ec2-user group=www CHECKMODE=True
   - name: copy index page
     copy: src=/SREChallenge/application/index.html dest=/var/www/html/Sample/index.html backup=yes
     notify:
     - restart apache
   - name: ensure apache is running (and enable it at boot)
     service: name=httpd state=started enabled=yes

   - name: Transfer the script
     copy: src=/SREChallenge/scripts/hello.sh dest=/var/www/html/hello.sh mode=0777

   - name: Execute the script
     local_action: command sudo sh /var/www/html/hello.sh

  handlers:
   - name: restart apache
     service: name=httpd state=restarted
